# Generated by Django 2.1.1 on 2018-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addcity',
            fields=[
                ('id', models.IntegerField(default=6, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Adddonor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Addorg',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='addstate',
            fields=[
                ('id', models.IntegerField(default=6, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='suggetions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sug', models.CharField(max_length=50)),
                ('choice', models.CharField(max_length=50)),
            ],
        ),
    ]
