# Generated by Django 2.1.1 on 2018-11-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userregisteration',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('add', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=12)),
                ('password', models.IntegerField(default=10)),
            ],
        ),
        migrations.DeleteModel(
            name='userregister',
        ),
    ]
