# Generated by Django 2.1.1 on 2018-11-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181126_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Functiondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fun', models.CharField(max_length=50)),
            ],
        ),
    ]
