# Generated by Django 2.1.1 on 2018-11-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_nonveg150_nonveg200_nonveg300_nonveg350_nonveg400_veg150_veg200_veg300_veg350_veg400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonveg150',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='nonveg200',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='nonveg300',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='nonveg350',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='nonveg400',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='veg150',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='veg200',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='veg300',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='veg350',
            name='item_cost',
        ),
        migrations.RemoveField(
            model_name='veg400',
            name='item_cost',
        ),
        migrations.AddField(
            model_name='nonveg150',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonveg200',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonveg300',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonveg350',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonveg400',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veg150',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veg200',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veg300',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veg350',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veg400',
            name='item_plate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nonveg150',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nonveg200',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nonveg300',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nonveg400',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veg150',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veg200',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veg300',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veg350',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='veg400',
            name='item_id',
            field=models.IntegerField(default=5, primary_key=True, serialize=False),
        ),
    ]
