# Generated by Django 2.1.1 on 2018-11-27 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20181127_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functiondetails',
            name='date',
        ),
    ]
