# Generated by Django 2.1.1 on 2018-11-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_swetdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField()),
                ('d_add', models.CharField(max_length=500)),
                ('food_type', models.CharField(max_length=50)),
                ('d_date', models.DateField()),
                ('no_plates', models.IntegerField()),
            ],
        ),
    ]
