# Generated by Django 2.1.1 on 2018-11-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addscity',
            fields=[
                ('id', models.IntegerField(default=6, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='addstate',
            fields=[
                ('id', models.IntegerField(default=8, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('Addcity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addscity')),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='organisation',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='suggetions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
