import pymysql
conn=pymysql.connect(host='localhost',user='root',passwd='root',db='sample')
cursor=conn.cursor()
cursor.execute("create table college(sid int,sname varchar(12),marks int)")
print('table inserted')
cursor.execute("insert into college values(111,'prasad',532)")
cursor.execute("insert into college values(222,'naidu',556)")
cursor.execute("insert into college values(333,'raju',530)")
cursor.execute("insert into college values(444,'ravi',539)")
cursor.execute("insert into college values(555,'rani',529)")
cursor.execute("insert into college values(666,'kumar',548)")
cursor.execute("insert into college values(777,'rani',535)")
cursor.execute("insert into college values(888,'jagadeesh',550)")
cursor.execute("insert into college values(999,'ramesh',450)")
cursor.execute("insert into college values(121,'suresh',490)")
cursor.execute("insert into college values(131,'umesh',439)")
cursor.execute("insert into college values(141,'eswar',500)")
print('rows are inserted')
conn.commit()
conn.close()