# Generated by Django 2.1.1 on 2018-12-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companyregister',
            fields=[
                ('c_id', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('c_hrname', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_contact', models.IntegerField(default=10)),
                ('c_purpose', models.CharField(max_length=50)),
                ('c_address', models.CharField(max_length=100)),
                ('c_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('CourseName', models.CharField(max_length=50)),
                ('CourseId', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('CourseFee', models.IntegerField(default=5)),
                ('CourseDuration', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='faculity',
            fields=[
                ('id', models.IntegerField(default=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('cno', models.IntegerField(default=10)),
                ('course', models.CharField(max_length=30)),
                ('exp', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('cno', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('password', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
